In [5]:
import numpy as np
import pandas as pd
from sklearn import preprocessing
import matplotlib.pyplot as plt
plt.rc("font",size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, GridSearchCV
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid",color_codes=True)

In [7]:
dia = pd.read_csv("diabetes.csv")

In [9]:
dia.head(3)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1

In [11]:
dia.shape

(768, 9)

In [13]:
dia.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [15]:
#np.where
#pd.cut()
#pd.qcut()

In [17]:
dia.nunique()

Pregnancies                  17
Glucose                     136
BloodPressure                47
SkinThickness                51
Insulin                     186
BMI                         248
DiabetesPedigreeFunction    517
Age                          52
Outcome                       2
dtype: int64

In [19]:
dia.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [22]:
dia['glu_level'] = np.where(dia['Glucose']<=70, "Low",np.where(dia['Glucose']>=180,"High","Medium"))

In [24]:
dia.head(10)

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,glu_level
0,6,148,72,35,0,33.6,0.627,50,1,Medium
1,1,85,66,29,0,26.6,0.351,31,0,Medium
2,8,183,64,0,0,23.3,0.672,32,1,High
3,1,89,66,23,94,28.1,0.167,21,0,Medium
4,0,137,40,35,168,43.1,2.288,33,1,Medium
5,5,116,74,0,0,25.6,0.201,30,0,Medium
6,3,78,50,32,88,31.0,0.248,26,1,Medium
7,10,115,0,0,0,35.3,0.134,29,0,Medium
8,2,197,70,45,543,30.5,0.158,53,1,High
9,8,125,96,0,0,0.0,0.232,54,1,Medium

In [26]:
dia['BMI_level'] = np.where(dia['BMI']<16.0,"very_low",
                               np.where(dia['BMI']<25.0,"Normal",
                                    np.where(dia['BMI']<18.5,"Underweight",
                                       np.where(dia['BMI']<30.0,"Overweight",
                                            np.where(dia['BMI']>30,"Very_high","")))))

In [28]:
#pd.cut(dia['BMI'],bins=5,labels = ['very_low','low','normal','high','very_high'])
pd.cut(dia['BMI'],bins=5)

0      (26.84, 40.26]
1      (13.42, 26.84]
2      (13.42, 26.84]
3      (26.84, 40.26]
4      (40.26, 53.68]
            ...
763    (26.84, 40.26]
764    (26.84, 40.26]
765    (13.42, 26.84]
766    (26.84, 40.26]
767    (26.84, 40.26]
Name: BMI, Length: 768, dtype: category
Categories (5, interval[float64, right]): [(-0.0671, 13.42] < (13.42, 26.84] < (26.84, 40.26] < (40.26, 53.68] < (53.68, 67.1]]

In [30]:
dia

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,glu_level,BMI_level
0,6,148,72,35,0,33.6,0.627,50,1,Medium,Very_high
1,1,85,66,29,0,26.6,0.351,31,0,Medium,Overweight
2,8,183,64,0,0,23.3,0.672,32,1,High,Normal
3,1,89,66,23,94,28.1,0.167,21,0,Medium,Overweight
4,0,137,40,35,168,43.1,2.288,33,1,Medium,Very_high
...,...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,Medium,Very_high
764,2,122,70,27,0,36.8,0.340,27,0,Medium,Very_high
765,5,121,72,23,112,26.2,0.245,30,0,Medium,Overweight
766,1,126,60,0,0,30.1,0.349,47,1,Medium,Very_high
767,1,93,70,31,0,30.4,0.315,23,0,Medium,Very_high

In [32]:
dia2 = dia.copy()

In [34]:
dia2 = dia2.drop(columns = ['Glucose', 'BMI'])

In [36]:
dia2 = pd.get_dummies(dia, columns = ['glu_level','BMI_level'], dtype = int)   #one-hot encoding

In [38]:
dia2

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,glu_level_High,glu_level_Low,glu_level_Medium,BMI_level_,BMI_level_Normal,BMI_level_Overweight,BMI_level_Very_high,BMI_level_very_low
0,6,148,72,35,0,33.6,0.627,50,1,0,0,1,0,0,0,1,0
1,1,85,66,29,0,26.6,0.351,31,0,0,0,1,0,0,1,0,0
2,8,183,64,0,0,23.3,0.672,32,1,1,0,0,0,1,0,0,0
3,1,89,66,23,94,28.1,0.167,21,0,0,0,1,0,0,1,0,0
4,0,137,40,35,168,43.1,2.288,33,1,0,0,1,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0,0,0,1,0,0,0,1,0
764,2,122,70,27,0,36.8,0.340,27,0,0,0,1,0,0,0,1,0
765,5,121,72,23,112,26.2,0.245,30,0,0,0,1,0,0,1,0,0
766,1,126,60,0,0,30.1,0.349,47,1,0,0,1,0,0,0,1,0
767,1,93,70,31,0,30.4,0.315,23,0,0,0,1,0,0,0,1,0

In [40]:
len(dia2.columns)

17

In [42]:
dia2.shape

(768, 17)

In [44]:
dia2.columns

Index(['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin',
       'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome', 'glu_level_High',
       'glu_level_Low', 'glu_level_Medium', 'BMI_level_', 'BMI_level_Normal',
       'BMI_level_Overweight', 'BMI_level_Very_high', 'BMI_level_very_low'],
      dtype='object')

In [46]:
dia2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 17 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
 9   glu_level_High            768 non-null    int32
 10  glu_level_Low             768 non-null    int32
 11  glu_level_Medium          768 non-null    int32
 12  BMI_level_                768 non-null    int32
 13  BMI_level_Normal          768 non-null    int32
 14  BMI_level_Overweight      768 non-null    int32
 15  BMI_level_Very_high       768 non-null    int32
 16  BMI_level_very_low        768 non-null    int32
dtypes: float64(2), int32(8), int64(7)
memory usage: 78.1 KB

In [48]:
dia2.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome,glu_level_High,glu_level_Low,glu_level_Medium,BMI_level_,BMI_level_Normal,BMI_level_Overweight,BMI_level_Very_high,BMI_level_very_low
0,6,148,72,35,0,33.6,0.627,50,1,0,0,1,0,0,0,1,0
1,1,85,66,29,0,26.6,0.351,31,0,0,0,1,0,0,1,0,0
2,8,183,64,0,0,23.3,0.672,32,1,1,0,0,0,1,0,0,0
3,1,89,66,23,94,28.1,0.167,21,0,0,0,1,0,0,1,0,0
4,0,137,40,35,168,43.1,2.288,33,1,0,0,1,0,0,0,1,0

In [50]:
dia2.shape

(768, 17)

In [54]:
dia2 = dia2.drop(columns = ['Glucose', 'BMI'])

In [56]:
dia2.head()

,Pregnancies,BloodPressure,SkinThickness,Insulin,DiabetesPedigreeFunction,Age,Outcome,glu_level_High,glu_level_Low,glu_level_Medium,BMI_level_,BMI_level_Normal,BMI_level_Overweight,BMI_level_Very_high,BMI_level_very_low
0,6,72,35,0,0.627,50,1,0,0,1,0,0,0,1,0
1,1,66,29,0,0.351,31,0,0,0,1,0,0,1,0,0
2,8,64,0,0,0.672,32,1,1,0,0,0,1,0,0,0
3,1,66,23,94,0.167,21,0,0,0,1,0,0,1,0,0
4,0,40,35,168,2.288,33,1,0,0,1,0,0,0,1,0

In [58]:
dia2.shape

(768, 15)

In [60]:
dia2.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
763    False
764    False
765    False
766    False
767    False
Length: 768, dtype: bool

In [63]:
Q1 = dia2['Insulin'].quantile(0.25)
Q3 = dia2['Insulin'].quantile(0.75)
IQR = Q3 - Q1
dia2 = dia2[(dia2['Insulin'] >= Q1 - 1.5 * IQR) & (dia2['Insulin'] <= Q3 + 1.5*IQR)]

In [65]:
dia2.loc[:, 'Insulin'] = np.log1p(dia2['Insulin'])
dia2.loc[:, 'SkinThickness'] = np.sqrt(dia2['SkinThickness'])

C:\Users\dell\AppData\Local\Temp\ipykernel_18240\857178855.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0.         0.         0.         4.55387689 5.12989871 0.
 4.48863637 0.         0.         0.         0.         0.
 5.170484   0.         5.44241771 0.         4.4308168  4.57471098
 5.46383181 0.         0.         0.         4.99043259 4.75359019
 0.         4.94875989 4.7095302  0.         0.         5.50533154
 4.00733319 0.         0.         5.26269019 0.         0.
 0.         5.33753808 4.26267988 0.         0.         5.48479693
 0.         0.         0.         0.         0.         0.
 4.41884061 3.61091791 3.17805383 5.70711026 0.         5.72031178
 4.7095302  0.         4.96284463 0.         0.         0.
 4.8598124  0.         0.         0.         0.         3.66356165
 4.61512052 4.51085951 4.94875989 0.         5.60211882 0.
 0.         0.         0.         0.         0.         0.
 0.         4.27666612 0.         0.         4.83628191 0.
 4.27666612 4.7095302  0.         0.         5.17614973 3.8918203
 0.         4.17438727 5.433722   0.         4.34380542 4.17438727
 5.3981627  0.         0.         0.         3.71357207 0.
 5.03043792 0.         4.94875989 2.94443898 3.61091791 4.91265489
 3.63758616 0.         5.170484   0.         0.         0.
 0.         3.95124372 4.61512052 0.         4.61512052 0.
 0.         4.60517019 4.91265489 4.55387689 4.98360662 0.
 5.12989871 0.         5.420535   0.         3.91202301 4.94875989
 3.93182563 4.53259949 0.         0.         0.         4.15888308
 0.         5.65248918 0.         0.         4.78749174 0.
 0.         5.32300998 0.         5.04985601 0.         0.
 4.55387689 4.91265489 3.98898405 4.74493213 0.         4.66343909
 5.65599181 0.         0.         5.05624581 0.         0.
 0.         4.36944785 0.         4.87519732 0.         3.8918203
 4.02535169 4.87519732 0.         4.87519732 0.         0.
 0.         4.53259949 3.17805383 0.         0.         0.
 4.07753744 4.74493213 5.08140436 0.         4.55387689 0.
 0.         0.         5.35185813 0.         3.8918203  4.60517019
 5.7651911  0.         0.         0.         3.80666249 5.25227343
 0.         5.63835467 0.         4.47733681 0.         0.
 0.         0.         4.87519732 5.170484   5.60580207 4.86753445
 4.79579055 0.         0.         0.         0.         5.25227343
 4.04305127 3.49650756 0.         0.         3.98898405 0.
 3.63758616 0.         3.8286414  0.         5.26269019 0.
 0.         0.         0.         4.48863637 0.         5.17614973
 5.27299956 0.         0.         0.         0.         0.
 4.02535169 0.         5.55682806 0.         0.         0.
 5.01727984 4.87519732 0.         0.         0.         0.
 4.21950771 0.         0.         0.         0.         0.
 4.04305127 0.         3.8286414  0.         4.06044301 0.
 4.76217393 0.         5.63121178 0.         4.81218436 5.04985601
 0.         0.         4.91265489 5.3981627  3.91202301 4.33073334
 3.71357207 4.31748811 5.20948615 5.27299956 0.         4.79579055
 5.37527841 5.22035583 0.         0.         4.91265489 3.76120012
 0.         0.         4.66343909 4.89034913 5.00394631 5.19849703
 5.32787617 0.         5.00394631 4.57471098 4.4543473  0.
 4.55387689 4.17438727 0.         4.94875989 0.         5.44673737
 0.         0.         3.40119738 0.         5.12989871 5.05624581
 0.         4.79579055 4.2341065  0.         3.97029191 0.
 0.         4.07753744 5.54517744 0.         0.         5.14749448
 0.         4.66343909 4.30406509 0.         0.         0.
 4.69134788 4.4308168  0.         4.31748811 0.         0.
 0.         0.         3.78418963 0.         0.         5.12396398
 0.         4.00733319 5.52146092 0.         0.         0.
 5.68357977 4.4308168  0.         0.         4.20469262 4.94875989
 4.49980967 4.20469262 4.55387689 5.0689042  4.44265126 4.33073334
 0.         4.29045944 4.41884061 0.         5.20948615 4.09434456
 4.7095302  3.93182563 0.         0.         5.65599181 4.40671925
 5.28320373 0.         4.47733681 0.         5.62040087 4.75359019
 0.         0.         0.         0.         0.         4.48863637
 0.         0.         5.11198779 0.         0.         0.
 0.         5.17614973 5.73979291 4.12713439 5.12396398 0.
 0.         0.         4.75359019 5.14166356 4.34380542 4.36944785
 0.         5.35185813 5.62762111 0.         5.19849703 4.98360662
 5.19849703 0.         4.4543473  4.11087386 0.         0.
 0.         0.         0.         0.         0.         0.
 3.93182563 4.79579055 0.         0.         2.7080502  4.26267988
 4.53259949 4.17438727 4.15888308 4.56434819 0.         5.35185813
 0.         4.66343909 0.         0.         4.27666612 5.47227067
 4.11087386 4.04305127 0.         3.91202301 0.         0.
 4.66343909 3.61091791 4.61512052 0.         4.94875989 0.
 0.         0.         0.         0.         0.         5.25749537
 4.7095302  4.33073334 0.         0.         3.91202301 4.83628191
 0.         5.52545294 5.58349631 0.         0.         4.20469262
 0.         0.         4.81218436 0.         0.         0.
 4.34380542 4.98360662 5.26785816 4.27666612 0.         0.
 4.38202663 0.         0.         4.51085951 5.14166356 4.34380542
 0.         0.         5.35185813 0.         0.         4.46590812
 4.66343909 5.11198779 0.         0.         4.20469262 4.87519732
 0.         0.         0.         0.         4.41884061 4.66343909
 5.24174702 0.         4.67282883 0.         4.18965474 0.
 4.04305127 0.         0.         0.         5.35185813 5.04985601
 5.37527841 5.25227343 0.         4.04305127 4.34380542 5.420535
 5.33753808 5.11799381 4.21950771 0.         0.         4.67282883
 0.         3.80666249 4.75359019 5.37527841 0.         0.
 0.         0.         0.         5.6167711  4.35670883 4.00733319
 0.         4.48863637 2.94443898 4.84418709 4.84418709 5.11198779
 0.         0.         3.80666249 4.79579055 4.15888308 4.87519732
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         5.05624581 0.
 0.         4.94875989 0.         4.75359019 5.44241771 5.22574667
 0.         3.25809654 0.         4.79579055 0.         0.
 0.         4.84418709 0.         0.         5.68357977 3.73766962
 5.6094718  5.20948615 5.0689042  5.27299956 0.         4.97673374
 0.         0.         2.77258872 0.         0.         5.08140436
 0.         0.         4.75359019 0.         4.00733319 0.
 0.         0.         0.         0.         4.51085951 0.
 5.21493576 0.         0.         0.         4.20469262 4.52178858
 3.8501476  4.66343909 0.         0.         0.         5.03043792
 4.97673374 5.07517382 4.87519732 0.         4.61512052 4.67282883
 4.35670883 0.         4.91265489 4.51085951 5.30330491 0.
 4.26267988 0.         0.         5.44673737 4.87519732 0.
 4.89034913 0.         0.         5.25227343 4.61512052 5.12989871
 0.         3.91202301 5.48479693 0.         0.         0.
 0.         0.         5.58349631 3.8286414  0.         4.66343909
 0.         0.         5.32787617 0.         0.         5.19849703
 5.19849703 0.         0.         4.56434819 4.83628191 0.
 4.83628191 0.         5.04985601 0.         5.30330491 0.
 0.         0.         4.61512052 0.         0.         0.
 5.08140436 3.13549422 0.         5.6767538  0.         5.22574667
 0.         5.18738581 0.         0.         5.30330491 4.85203026
 4.66343909 0.         0.         5.19849703 0.         0.
 0.         4.38202663 0.         4.79579055 5.11198779 0.
 0.         4.79579055 0.         5.08140436 0.         5.01727984
 4.55387689 4.76217393 0.         4.94875989 4.66343909 0.
 4.06044301 5.30330491 0.         0.         4.31748811 0.
 0.         4.7095302  0.         0.         0.         0.
 2.83321334 0.         0.         5.19849703 0.         4.72738782
 0.         0.        ]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  dia2.loc[:, 'Insulin'] = np.log1p(dia2['Insulin'])
C:\Users\dell\AppData\Local\Temp\ipykernel_18240\857178855.py:2: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[5.91607978 5.38516481 0.         4.79583152 5.91607978 0.
 5.65685425 0.         0.         0.         0.         0.
 4.35889894 0.         6.8556546  0.         6.164414   5.47722558
 6.40312424 0.         0.         5.91607978 5.74456265 5.09901951
 0.         3.87298335 4.35889894 0.         5.09901951 6.
 3.31662479 0.         5.56776436 5.74456265 0.         6.08276253
 6.4807407  6.8556546  5.         0.         4.24264069 4.89897949
 0.         6.244998   0.         5.19615242 5.65685425 0.
 3.31662479 3.87298335 4.58257569 5.83095189 3.16227766 6.244998
 7.74596669 0.         6.40312424 0.         0.         0.
 5.83095189 0.         5.19615242 5.47722558 0.         3.60555128
 5.19615242 4.47213595 5.91607978 0.         4.47213595 5.47722558
 4.47213595 0.         5.74456265 0.         4.69041576 3.60555128
 0.         5.09901951 5.29150262 0.         5.38516481 7.34846923
 5.         5.65685425 4.35889894 0.         3.87298335 6.32455532
 0.         4.24264069 5.19615242 5.29150262 4.24264069 5.47722558
 7.14142843 0.         0.         0.         4.24264069 0.
 5.38516481 0.         5.29150262 5.56776436 5.         5.74456265
 5.83095189 0.         5.65685425 0.         0.         0.
 4.79583152 3.87298335 7.48331477 6.244998   5.47722558 0.
 0.         6.4807407  5.47722558 6.         4.89897949 0.
 3.74165739 0.         6.08276253 5.56776436 3.60555128 4.47213595
 5.09901951 5.         0.         0.         5.47722558 5.09901951
 0.         5.56776436 4.79583152 6.08276253 5.91607978 0.
 4.12310563 7.07106781 0.         5.29150262 0.         6.63324958
 3.87298335 4.58257569 4.35889894 6.40312424 6.164414   6.32455532
 5.83095189 4.79583152 0.         4.24264069 5.         0.
 0.         3.46410162 0.         4.79583152 4.79583152 6.4807407
 4.89897949 6.4807407  0.         6.78232998 0.         0.
 0.         4.24264069 4.47213595 0.         0.         5.29150262
 6.40312424 6.244998   5.91607978 0.         6.63324958 0.
 0.         4.47213595 6.40312424 0.         3.60555128 6.63324958
 5.19615242 4.         0.         4.47213595 4.         5.65685425
 5.29150262 5.38516481 0.         5.19615242 5.74456265 4.69041576
 7.34846923 5.56776436 5.09901951 5.65685425 6.32455532 6.40312424
 5.47722558 4.69041576 0.         0.         0.         5.74456265
 3.87298335 5.19615242 0.         6.164414   5.56776436 0.
 5.         0.         5.29150262 0.         4.58257569 5.19615242
 4.58257569 0.         4.89897949 5.65685425 0.         4.69041576
 5.91607978 3.87298335 0.         4.35889894 0.         0.
 3.74165739 5.65685425 2.64575131 5.91607978 6.244998   4.69041576
 5.29150262 3.87298335 0.         5.65685425 3.87298335 0.
 4.24264069 0.         6.4807407  0.         0.         6.08276253
 5.65685425 0.         7.07106781 0.         7.21110255 4.89897949
 4.79583152 0.         3.16227766 0.         5.29150262 3.87298335
 0.         0.         5.09901951 6.244998   4.12310563 6.55743852
 5.38516481 5.47722558 6.08276253 6.70820393 0.         5.56776436
 5.38516481 5.         0.         0.         5.74456265 6.40312424
 0.         0.         6.08276253 4.79583152 3.74165739 4.35889894
 5.29150262 5.47722558 6.08276253 4.12310563 3.16227766 5.56776436
 4.69041576 3.31662479 0.         6.244998   0.         3.46410162
 5.47722558 4.47213595 5.74456265 5.65685425 4.58257569 5.65685425
 0.         6.         5.65685425 4.35889894 4.         0.
 0.         4.24264069 6.55743852 0.         0.         5.83095189
 0.         3.60555128 4.58257569 5.91607978 0.         0.
 6.         4.35889894 0.         4.35889894 5.65685425 0.
 0.         5.29150262 3.46410162 0.         0.         6.32455532
 5.47722558 6.32455532 6.         0.         6.08276253 0.
 5.         5.29150262 0.         4.12310563 4.         5.29150262
 4.79583152 4.69041576 6.32455532 6.55743852 3.87298335 6.08276253
 0.         6.244998   5.47722558 4.69041576 2.82842712 4.24264069
 4.89897949 3.60555128 5.38516481 6.         5.09901951 4.79583152
 5.38516481 0.         3.46410162 0.         4.89897949 5.83095189
 6.32455532 0.         5.56776436 0.         0.         6.40312424
 5.         0.         5.65685425 0.         0.         0.
 6.244998   5.47722558 4.79583152 4.69041576 5.91607978 4.58257569
 5.65685425 0.         5.38516481 6.40312424 4.24264069 6.78232998
 4.69041576 5.65685425 6.244998   0.         5.47722558 6.78232998
 5.         0.         4.         3.31662479 0.         2.82842712
 0.         5.74456265 0.         3.87298335 0.         5.
 4.79583152 5.19615242 0.         3.46410162 7.93725393 3.46410162
 6.70820393 6.08276253 4.24264069 3.60555128 0.         5.65685425
 0.         5.29150262 5.47722558 0.         5.29150262 6.92820323
 5.74456265 4.69041576 0.         6.32455532 5.47722558 0.
 3.60555128 3.16227766 6.         0.         6.40312424 6.32455532
 6.164414   5.19615242 0.         0.         5.19615242 6.70820393
 4.12310563 6.164414   5.56776436 6.08276253 4.69041576 5.56776436
 0.         6.4807407  5.65685425 4.12310563 0.         5.29150262
 5.47722558 6.164414   4.24264069 0.         0.         0.
 3.87298335 5.74456265 5.65685425 4.35889894 5.65685425 6.40312424
 5.         6.244998   0.         5.09901951 4.79583152 4.79583152
 0.         5.56776436 4.12310563 0.         0.         4.35889894
 4.24264069 5.83095189 0.         0.         5.65685425 5.74456265
 0.         0.         0.         4.24264069 4.35889894 3.87298335
 5.56776436 0.         4.24264069 0.         7.21110255 0.
 5.47722558 0.         0.         0.         6.08276253 7.
 6.32455532 5.         5.65685425 4.79583152 5.38516481 5.91607978
 5.19615242 4.58257569 6.55743852 5.56776436 5.29150262 5.47722558
 0.         4.89897949 4.79583152 5.74456265 6.32455532 0.
 6.32455532 0.         0.         5.65685425 5.83095189 4.35889894
 0.         3.74165739 5.47722558 5.65685425 5.38516481 5.47722558
 0.         0.         5.56776436 4.12310563 6.8556546  4.47213595
 0.         0.         9.94987437 6.78232998 5.19615242 4.12310563
 0.         3.31662479 0.         0.         5.19615242 0.
 6.32455532 7.07106781 0.         4.69041576 6.70820393 3.74165739
 0.         4.35889894 0.         4.24264069 4.35889894 0.
 6.         5.38516481 0.         5.65685425 6.4807407  5.
 6.244998   3.60555128 4.58257569 4.69041576 5.29150262 5.09901951
 0.         0.         3.60555128 4.89897949 0.         6.4807407
 4.47213595 0.         5.19615242 0.         6.8556546  0.
 0.         0.         4.69041576 0.         6.32455532 0.
 4.12310563 0.         0.         0.         4.24264069 5.65685425
 3.46410162 4.12310563 0.         0.         0.         5.47722558
 4.12310563 6.         5.91607978 5.         5.         4.79583152
 6.32455532 0.         5.29150262 5.91607978 6.92820323 0.
 5.56776436 0.         6.55743852 6.78232998 6.78232998 6.244998
 6.70820393 4.24264069 5.19615242 5.74456265 5.47722558 5.09901951
 3.16227766 4.79583152 5.91607978 0.         0.         0.
 0.         0.         4.12310563 5.29150262 6.         6.244998
 0.         0.         5.09901951 0.         4.35889894 5.09901951
 6.78232998 0.         0.         5.65685425 7.         0.
 4.35889894 0.         3.31662479 0.         5.19615242 5.56776436
 5.38516481 0.         4.47213595 6.         0.         0.
 5.65685425 5.19615242 6.         4.47213595 0.         6.244998
 4.24264069 6.78232998 5.19615242 4.35889894 6.         5.38516481
 5.47722558 0.         6.32455532 5.38516481 5.09901951 0.
 0.         4.79583152 0.         6.08276253 5.19615242 0.
 5.65685425 5.19615242 4.79583152 4.12310563 0.         6.08276253
 4.47213595 4.24264069 0.         6.08276253 5.74456265 6.40312424
 6.40312424 4.69041576 0.         0.         6.244998   4.89897949
 5.65685425 6.244998   6.40312424 0.         0.         0.
 5.09901951 5.56776436 0.         6.92820323 5.19615242 4.79583152
 0.         5.56776436]' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  dia2.loc[:, 'SkinThickness'] = np.sqrt(dia2['SkinThickness'])

In [69]:
#Age bins

dia2['AgeGroup'] = pd.cut(dia2['Age'],
                         bins = [20,30,40,50,60,100],
                         labels = ["20-30","30-40","40-50","50-60","60+"])

#Convert categorical bins to dummy variables
dia2 = pd.get_dummies(dia2, columns = ["AgeGroup"], drop_first = True)

In [71]:
from sklearn.model_selection import train_test_split

X = dia2.drop("Outcome", axis = 1)
y = dia2["Outcome"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [77]:
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import accuracy_score

models = {
    "GaussianNB" : GaussianNB(),
    "Bernoulli" : BernoulliNB()
}

results = {}
for name, model in models.items():
    model.fit(X_train, y_train)

    #Predictions
    y_train_pred = model.predict(X_train)
    y_test_pred =  model.predict(X_test)

    #Accuracy
    train_acc = accuracy_score(y_train, y_train_pred)
    test_acc = accuracy_score(y_test, y_test_pred)

    results[name] = {"Train accuracy": train_acc,  "Test accuracy": test_acc}
    print(f"{name} → Train: {train_acc : .4f}, Test: {test_acc:.4f}")

GaussianNB → Train:  0.7411, Test: 0.7347
Bernoulli → Train:  0.7428, Test: 0.7551